CREATE TABLE USUARIOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPOUSUARIO VARCHAR2(25) NOT NULL,
    LOGIN VARCHAR2(160) UNIQUE NOT NULL,
    SENHA VARCHAR2(200) NOT NULL
);
CREATE TABLE CLIENTES(
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    IDADE NUMBER,
    CPF VARCHAR2(14),
    SEXO VARCHAR2(20),
    SALDO NUMBER,
    CONSTRAINT FK_CLIENTE_USER FOREIGN KEY (ID) REFERENCES USUARIOS(ID)
);
CREATE TABLE USUARIOS(
    ID NUMBER PRIMARY KEY, 
    CPF VARCHAR2(14), 
    IDADE NUMBER, 
    SEXO VARCHAR2(10), 
    LUGARES_OFERTADOS VARCHAR2(500), CONSTRAINT FK_ADMIN_USER FOREIGN KEY (ID) REFERENCES USUARIOS(ID)
);
     
