
CREATE TABLE USUARIOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPOUSUARIO VARCHAR2(25) NOT NULL, 
    LOGIN VARCHAR2(160) UNIQUE NOT NULL,
    SENHA VARCHAR2(200) NOT NULL
);


CREATE TABLE CLIENTES (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    IDADE NUMBER NOT NULL,
    CPF VARCHAR2(14) UNIQUE NOT NULL,
    SEXO VARCHAR2(20),
    SALDO NUMBER(10,2) DEFAULT 0,
    RESERVA_ATIVA_ID NUMBER,

    CONSTRAINT FK_CLIENTE_USUARIO
        FOREIGN KEY (ID)
        REFERENCES USUARIOS(ID)
        ON DELETE CASCADE
);


CREATE TABLE LUGARES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    LOCALIZACAO VARCHAR2(150),
    PRECO NUMBER(10,2) NOT NULL,
    DISPONIVEL NUMBER(1) DEFAULT 1, 
    ATIVO NUMBER(1) DEFAULT 1       
);


CREATE TABLE RESERVAS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENTE_ID NUMBER NOT NULL,
    LUGAR_ID NUMBER NOT NULL,
    STATUS VARCHAR2(20) NOT NULL, 
    DATA_RESERVA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_FINALIZACAO TIMESTAMP,

    CONSTRAINT FK_RES_CLIENTE
        FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID),

    CONSTRAINT FK_RES_LUGAR
        FOREIGN KEY (LUGAR_ID) REFERENCES LUGARES(ID)
);


ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTE_RESERVA_ATIVA
FOREIGN KEY (RESERVA_ATIVA_ID)
REFERENCES RESERVAS(ID);


CREATE TABLE HISTORICO_RESERVAS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENTE_ID NUMBER NOT NULL,
    LUGAR_ID NUMBER NOT NULL,
    STATUS VARCHAR2(20) NOT NULL, 
    DATA_EVENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_HIST_CLIENTE
        FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID),

    CONSTRAINT FK_HIST_LUGAR
        FOREIGN KEY (LUGAR_ID) REFERENCES LUGARES(ID)
);
INSERT INTO usuarios (login, senha, tipo_usuario)
VALUES ('admin', '56789', 'ADMIN');

INSERT INTO usuarios (login, senha, tipo_usuario)
VALUES ('cliente', '01234', 'CLIENTE');
