CREATE TABLE USUARIOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPOUSUARIO VARCHAR2(25) NOT NULL,
    LOGIN VARCHAR2(160) UNIQUE NOT NULL,
    SENHA VARCHAR2(200) NOT NULL
);
CREATE TABLE CLIENTES(
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    IDADE NUMBER,
    CPF VARCHAR2(14),
    SEXO VARCHAR2(20),
    SALDO NUMBER,
    CONSTRAINT FK_CLIENTE_USER
        FOREIGN KEY (ID)
        REFERENCES USUARIOS(ID)
        ON DELETE CASCADE
);
CREATE TABLE ADMINISTRADORES(
    ID NUMBER PRIMARY KEY,
    CPF VARCHAR2(14),
    IDADE NUMBER,
    SEXO VARCHAR2(10),
    LUGARES_OFERTADOS VARCHAR2(500),
    CONSTRAINT FK_ADMIN_USER
        FOREIGN KEY (ID)
        REFERENCES USUARIOS(ID)
        ON DELETE CASCADE
);
CREATE TABLE LUGARES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100),
    DISPONIVEL NUMBER(1) -- 1 = SIM | 0 = NÃO
);

CREATE TABLE RESERVAS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENTE_ID NUMBER,
    LUGAR_ID NUMBER,
    STATUS VARCHAR2(20), -- ATIVA | FINALIZADA
    CONSTRAINT FK_RES_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID),
    CONSTRAINT FK_RES_LUGAR FOREIGN KEY (LUGAR_ID) REFERENCES LUGARES(ID)
);
     
